// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: messages.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
insert into messages(user_id, room_id, text) 
values ($1, $2, $3)
returning message_id, user_id, room_id, text, multimedia, is_read, read_at, created_at
`

type CreateMessageParams struct {
	UserID uuid.UUID   `json:"user_id"`
	RoomID uuid.UUID   `json:"room_id"`
	Text   pgtype.Text `json:"text"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.UserID, arg.RoomID, arg.Text)
	var i Message
	err := row.Scan(
		&i.MessageID,
		&i.UserID,
		&i.RoomID,
		&i.Text,
		&i.Multimedia,
		&i.IsRead,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}
