// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: rooms.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :exec
insert into rooms(name, description, room_type) 
values ($1, $2, $3)
`

type CreateRoomParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	RoomType    string      `json:"room_type"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom, arg.Name, arg.Description, arg.RoomType)
	return err
}
