[package]
name = "bytechat"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.1", features = ["with-axum"] }
askama_axum = "0.4.0"
axum = {version = "0.7.4", features = ["ws"]}
password-auth = "1.0.0"
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
shuttle-axum = "0.45.0"
shuttle-runtime = "0.45.0"
shuttle-shared-db = { version = "0.45.0", features = ["postgres", "sqlx"] }
sqlx = "0.7.4"
tokio = "1.28.2"
tokio-stream = { version = "0.1.14", features = ["sync"] }
tower-cookies = "0.10.0"
